//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Generic.rc
//
#define IDR_MENU1                       101
#define CHDMENU                         103

#define MENU_ABOUT		1
#define TESTAPIICON                     200
#define MENU_KILL                       40001
#define MENU_COM_READ                   40002
#define IDM_START                       40003
#define MENU_COM_WRITE                  40003
#define  MENU_CREATE                     40004        
#define IDM_LOCKUP                      65534
#define IDM_KILL                        65535

#define IDM_COMM_READ                   40007
#define IDM_COMM_WRITE                  40008

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40007
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
